version: "3.8"

services:
  web:
    container_name: web
    build: .
    ports:
      - 8000:8000
    privileged: true
    volumes:
      - ./code:/code
    tty: true
    stdin_open: true
    depends_on: 
      - db

  db:
    container_name: drf_db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: drf
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: ‘yes’
    volumes: 
      - ./mysql:/var/lib/mysql
    ports: 
      - 33306:3306
