version: "3.8"

services:
  web:
    container_name: web
    build: .
    ports:
      - 8000:8000
    privileged: true
    volumes:
      - ./code:/code
    tty: true
    stdin_open: true
